version: "3.8"
services:
  covid:
    container_name: mycovid
    image: mycovid
    ports:
      - 80:80


  
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      # необходимо открыть порты, которые используются плагином forward
      - 24224:24224
      - 24224:24224/udp
    volumes:
      # добавляем конфигурацию в контейнер
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
